config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users

  resources :products

  resources :orders, only: [:index, :show, :create, :update] do
    resources :payments, only: :new
  end

  get "/cart", to: "carts#show"

  resources :carts, only: [:show] do
    resources :cart_items, only: [:destroy]
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_items

  def clear
    self.cart_items.each{ |ci| ci.destroy}
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  def remove_from_cart
    self.destroy
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :order_items
  monetize :amount_cents
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
	has_one_attached :cover_photo
	monetize :price_cents
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  after_create :create_user_cart
  has_many :orders
  has_one :cart

  def create_user_cart
    cart = Cart.new(user: self, guest?: false)
    cart.save!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_cart
  before_action :store_user_location!, if: :storable_location?

  include Pundit

  def set_cart
    # force session load in the meantime i fix session not being loaded
    session["init"] = true
    if user_signed_in?
      @cart = current_user.cart
    else
      if Cart.exists?(id: session[:cart_id])
        @cart = Cart.find(session[:cart_id])
      else
        @cart = Cart.new()
        @cart.save!
        session[:cart_id] = @cart.id
      end
    end
  end

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    store_location_for(:user, request.fullpath)
  end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_path
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart

  def show
    @order = Order.new
    @total = 0
    @cart.cart_items.each do |ci|
      @total += ci.quantity * ci.price
    end
  end

  def add_to_cart
    @product = Product.find(params[:product_id])
    if CartItem.exists?(product: @product, cart: @cart, price: @product.price)
      c = CartItem.where(product: @product, cart: @cart, price: @product.price)[0]
      c.update(quantity: c.quantity += 1)
    else
      c = CartItem.create(product: @product, cart: @cart, price: @product.price, quantity: 1)
    end
    redirect_to cart_path, cart_add: "#{c.id} created!"
  end

  private

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    if user_signed_in?
      @order = current_user.orders.find(params[:id])
    else
      @order = Order.where(customer_session_id: session[:session_id]).find(params[:id])
    end
  end

  def index
    if user_signed_in?
      @orders = Order.where(user: current_user)
    else
      @orders = Order.where(customer_session_id: session[:session_id])
    end
  end

  def create

    @product = Product.find(params[:product_id])
    @order = Order.create!(amount: @product.price, status: 'pending', user: current_user)

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: @product.name,
        images: [@product.cover_photo.key],
        amount: @product.price_cents,
        currency: 'usd',
        quantity: 1
        }],
        success_url: order_url(@order),
        cancel_url: order_url(@order)
      );

    @order.update(checkout_session_id: session.id)
    redirect_to new_order_payment_path(@order)
  end

  private

  def order_params
    params.require(:order).permit(:amount, :status, :user)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :set_cart
  def home
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @order = current_user.orders.where(status: 'pending').find(params[:order_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @order = Order.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    authorize @product, :create?
    @product.save
    if @product.save
      redirect_to product_path(@product)
    else
      render product_new
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock, :made_to_order?, :available, :cover_photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/show.html.erb
<div class="wrapper">
  <h4>Your Cart </h4>
  <% if @cart.cart_items.blank? %>
    <p>Your cart is empty <%= link_to "Keep Shopping!", products_path %></p>
  <% else %>
    <div class="d-flex">
      <div class="col-8">
        <div class="d-flex">
          <div class="col-3"><b> Product </b></div>
          <div class="col-3"><b> Price </b></div>
          <div class="col-3"><b> Quantity </b></div>
          <div class="col-3"><b> Total </b></div>
        </div>
        <% @cart.cart_items.each do |c| %>
          <div class="d-flex">
            <div class="col-3">
              <p><%= c.product.name %></p>
            </div>
            <div class="col-3">
              <p><%= c.price %></p>
            </div>
            <div class="col-3 d-flex">
              <%= link_to "-", cart_cart_item_path(@cart, c), method: :delete %>
              <p><%= c.quantity %></p>
              <%= link_to "+", cart_cart_item_path(@cart, c), method: :delete %>
            </div>
            <div class="col-3">
              <p><%= c.price * c.quantity %></p>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-4">
        <div class="d-flex">
          <div class="col-12">
            <h5>Total</h5>
            <p><b><%= @total %></b></p>
            <%= simple_form_for(@order) do |f| %>
              <%= f.submit "Proceed to Checkout", class: "button wide-button primary-button" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>moni</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="body">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<div class="wrapper">
  <div class="row">
    <% @orders.each do |order| %>
      <div class="product-card-wrapper col-12">
        <%= link_to order_path(order) do %>
          <div class="product-card">
            <h1>Order #<%= order.id %> <small><span class="badge badge-primary"><%= order.status %></span></small></h1>
            <p><strong>ISSUED ON</strong> <%= order.created_at.to_date %></p>
            <p><strong><%= order.order_items.count %> Items</strong> </p>
            <p><strong>ORDER TOTAL:</strong> <%= order.price %></p>
            <p><strong>ORDER STATUS:</strong> <%= order.status %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<h1>order show</h1>

app/views/pages/home.html.erb
<div class="placeholder-div">
  <h1> landing page</h1>
</div>

app/views/payments/new.html.erb
<div class="container">
  <div class="row py-4">
    <div class="col">
      <h1>Checkout summary</h1>
      <button id="pay" class="btn btn-primary">Pay</button>
      <script src="https://js.stripe.com/v3/"></script>
      <script>
        const paymentButton = document.getElementById('pay');
        paymentButton.addEventListener('click', () => {
          const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
          stripe.redirectToCheckout({
            sessionId: '<%= @order.checkout_session_id %>'
          });
        });
      </script>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="wrapper">
  <div class="row">
    <% @products.each do |product| %>
      <div class="product-card-wrapper col-12 col-sm-6 col-md-6 col-lg-4 col-xl-4">
        <%= link_to product_path(product) do %>
          <div class="product-card">
            <%= cl_image_tag product.cover_photo.key, class: "product-index-image" %>
            <p><%= product.name %></p>
            <p> <%= humanized_money_with_symbol(product.price) %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="wrapper">
  <%= simple_form_for(@product) do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :stock %>
    <%= f.input :made_to_order? %>
    <%= f.input :price %>
    <%= f.file_field :cover_photo %>
    <%= f.submit %>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="wrapper">
  <div class="row">
    <div class="col-12 col-md-7">
      <%= cl_image_tag @product.cover_photo.key, :crop=>"fill", class: "product-show-image" %>
    </div>
    <div class="col-12 col-md-5">
      <div class="product-info">
        <div class="col-12">
          <p><%= @product.name %></p>
          <p><%= humanized_money_with_symbol(@product.price) %></p>
        </div>
      </div>
      <div class="product-pricing">
        <div class="col-12">
          <p><%= @product.description %></p>
        </div>
      </div>
      <div class="product-purchasing row">
        <%# <div class="col-6">
          <button class="button primary-button wide-button">Add to Cart</button>
        </div> %>
        <div class="col-12">
          <%= form_tag orders_path do %>
            <%= hidden_field_tag 'product_id', @product.id %>
            <%= hidden_field_tag 'purchase_method', "direct" %>
            <%= submit_tag 'Purchase', class: 'button primary-button wide-button' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar-left d-flex">
    <%= link_to "MONI", root_path, class: "navbar-link" %>
  </div>
  <div class="navbar-right d-flex">
    <% if policy(Product).create? %>
      <%= link_to "NEW PRODUCT", new_product_path, class: "navbar-link" %>
    <% end %>
    <%= link_to "BROWSE", products_path, class: "navbar-link" %>
    <%= link_to "ORDERS", orders_path, class: "navbar-link" %>
    <%= link_to "CART (#{@cart.cart_items.count})", "/cart", class: "navbar-link" %>
    <% if current_user %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "navbar-link" %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path, class: "navbar-link" %>

    <% end %>
  </div>
</div>